services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - frontend
      - game-server
      # - backend
    networks:
      - network

  game-server:
    build:
      context: .
      dockerfile: ./game/server/Dockerfile
    container_name: game-server
    restart: unless-stopped
    networks:
      - network
    ports:
      - "9001:9001"

  # game-ai:
  #   build:
  #     context: .
  #     dockerfile: ./game/ai/Dockerfile
  #   restart: unless-stopped
  #   networks:
  #     - network

  # backend:
  #   build:
  #     context: ./backend
  #   restart: unless-stopped
  #   environment:
  #     - name=value
  #   depends_on:
  #     - database
  #     - redis
  #   networks:
  #     - network

  # database:
  #   image:
  #   environment:
  #     - name=value
  #   volumes:
  #     -
  #   networks:
  #     - network

  # redis:
  #   image:
  #   networks:
  #     - network

networks:
  network:
    driver: bridge

# volumes:
#   pgdata:

# secrets:
